<?php

define( "PENCI_PODCAST_IMPORTER_NAME", 'Penci Podcast Importer' );
define( "PENCI_PODCAST_IMPORTER_NAME_SHORT", 'Podcast Importer' );
define( "PENCI_PODCAST_IMPORTER_ALIAS", 'podcast_importer_pencipdc' );
define( "PENCI_PODCAST_IMPORTER_PREFIX", 'pencipdc-importer' );

define( "PENCI_PODCAST_IMPORTER_SETTINGS_PERMISSION_CAP", 'manage_options' );
define( "PENCI_PODCAST_IMPORTER_FEED_PERMISSION_CAP", 'manage_options' );
define( "PENCI_PODCAST_IMPORTER_REST_API_PREFIX", PENCI_PODCAST_IMPORTER_PREFIX );
define( 'PENCI_PODCAST_IMPORTER_LANGUAGE_DIRECTORY', basename( dirname( PENCI_PODCAST_IMPORTER_BASE_FILE_PATH ) ) . '/languages/'  );

define( "PENCI_PODCAST_IMPORTER_POST_TYPE_IMPORT", 'pencipdc_import' );
define( "PENCI_PODCAST_IMPORTER_CRON_JOB_FREQUENCY", 'hourly' );
define( "PENCI_PODCAST_IMPORTER_CRON_JOB_PROCESS_FREQUENCY", 'five_minutes' );

if( !defined( 'PENCI_PODCAST_IMPORTER_CRON_JOB_IMAGE_IMPORT_LIMIT' ) )
  define( "PENCI_PODCAST_IMPORTER_CRON_JOB_IMAGE_IMPORT_LIMIT", 10 );

if( !defined( 'PENCI_PODCAST_IMPORTER_SETUP_IMPORT_PER_REQUEST' ) )
  define( "PENCI_PODCAST_IMPORTER_SETUP_IMPORT_PER_REQUEST", 100 );

define( "PENCI_PODCAST_IMPORTER_SCHEDULER_FEED_GROUP", PENCI_PODCAST_IMPORTER_ALIAS . '_scheduler_feed' );
define( "PENCI_PODCAST_IMPORTER_SCHEDULER_FEED_PREFIX", PENCI_PODCAST_IMPORTER_ALIAS . '_scheduler_feed_' );